name: Build with Nuitka

on:
    push:
        branches: ["main"]
    workflow_dispatch:

env:
    PROJECT_NAME: flet_nuitka_uv_arena
    PYTHON_VERSION: "3.10"
    UV_VERSION: "0.7.2"

jobs:
    build:
        name: Build (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      ext: ""
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                      ext: ".exe"
                    - os: macos-latest
                      target: x86_64-apple-darwin
                      ext: ""
                    - os: macos-latest
                      target: aarch64-apple-darwin
                      ext: ""

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            # 3. 安装uv（全局安装）
            - name: Install uv globally
              uses: astral-sh/setup-uv@v5
              with:
                  # Install a specific version of uv.
                  version: ${{ env.UV_VERSION }}

            # 4. 安装依赖
            - name: Sync dependencies
              run: |
                  uv sync

            - name: Build with Nuitka
              shell: bash
              run: |
                  output_name="dist/app_${{ matrix.target }}${{ matrix.ext }}"
                  uv run nuitka \
                    --standalone \
                    --onefile \
                    --windows-console-mode=disable \
                    --output-dir=dist \
                    --output-filename="$output_name" \
                    --include-package=flet \
                    --include-data-dir=assets=assets \
                    src/main.py

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.os }}-${{ matrix.target }}-app
                  path: dist/
                  if-no-files-found: error
